version: '3'

services:
  rabbitProduct:
    image: rabbitmq:3-management
    container_name: rabbitProduct
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user1234
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - back-end
  
  dbProduct:
    image: postgres:11-alpine
    container_name: dbProduct
    environment:
      - POSTGRES_PASSWORD=ZjBybUBsMXpAcg==
      - POSTGRES_USER=productAdmin
      - POSTGRES_DB=Product-DEV
    ports:
      - 5432:5432
    networks:
      - back-end
 
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - 10000:10000
    networks:
      - back-end  
      
  api:
    depends_on:
      - rabbitProduct
      - dbProduct
      - azurite
    image: api
    container_name: Product.API
    build:
     context: Product
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
    ports:
     - 8080:80    
    networks:
     - back-end
      
networks:
    back-end:
  